<a href="https://colab.research.google.com/github/aman5898/Data-Science-January/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5])

In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
print(arr.ndim)

1


In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr = np.array([1,2,3,4,5],dtype="uint8")

In [ ]:
arr.dtype

dtype('uint8')

In [ ]:
arr = np.array([1,2,3,4,5,6.6])

In [ ]:
arr.dtype

dtype('float64')

## Time

In [ ]:
lst = [1]*1000

In [ ]:
print(lst)
print(len(lst))
print(type(lst))

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

In [ ]:
arr = np.ones(10000,dtype="uint8")

In [ ]:
print(arr)

In [ ]:
%timeit sum(lst)

10000 loops, best of 5: 73.2 µs per loop


In [ ]:
%timeit arr.sum()

The slowest run took 13.14 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 13.7 µs per loop


In [ ]:
%timeit sum(arr)

100 loops, best of 5: 2.27 ms per loop


Numpy stands for numerical Python.

It is a library of python to work with Arrays

In [29]:
arr = np.ones(5)

array([1., 1., 1., 1., 1.])

In [30]:
type(arr)

numpy.ndarray

In [32]:
arr.dtype

dtype('uint8')

In [34]:
arr = np.ones((3,4),dtype="uint8")

In [35]:
print(arr)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [38]:
arr = np.zeros((3,4),dtype="int8")

In [39]:
arr.shape

(3, 4)

In [44]:
arr = np.arange(2,10,2)

In [45]:
print(arr)

[2 4 6 8]


In [46]:
arr.shape

(4,)

## Slicing

numpy slicing is shallow copy python does deep copy

In [49]:
arr = np.arange(5,25,2)

In [50]:
print(arr)

[ 5  7  9 11 13 15 17 19 21 23]


In [51]:
arr[2:5]

array([ 9, 11, 13])

In [55]:
lst = [1,2,3,4,5]
lst2 = lst[2:4]
print(lst)
print(lst2)
lst2[0] = 1000
print(lst)
print(lst2)

[1, 2, 3, 4, 5]
[3, 4]
[1, 2, 3, 4, 5]
[1000, 4]


In [59]:
arr = np.array([1,2,3,4,5])
arr2 = arr[2:4]
print(arr)
print(arr2)
arr2[0] = 1000
print(arr)
print(arr2)

[1 2 3 4 5]
[3 4]
[   1    2 1000    4    5]
[1000    4]


In [60]:
arr = np.array([1,2,3,4,5])
arr2 = arr[2:4].copy()
print(arr)
print(arr2)
arr2[0] = 1000
print(arr)
print(arr2)

[1 2 3 4 5]
[3 4]
[1 2 3 4 5]
[1000    4]
