<a href="https://colab.research.google.com/github/aman5898/Data-Science-January/blob/main/Pandas/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

## Series

In [5]:
A = pd.Series([10,20,33,44])

In [6]:
A

0    10
1    20
2    33
3    44
dtype: int64

In [7]:
print(A.values)

[10 20 33 44]


In [8]:
type(A)

pandas.core.series.Series

In [9]:
type(A.values)

numpy.ndarray

In [10]:
print(A.index)

RangeIndex(start=0, stop=4, step=1)


In [11]:
print(type(A.index))

<class 'pandas.core.indexes.range.RangeIndex'>


In [15]:
A = pd.Series([10,20,30,"40"],index = ['a','b','c','d'])

In [32]:
A

a    10
b    20
c    30
d    40
dtype: object

In [23]:
print(A.values)

[10 20 30 '40']


In [27]:
arr = A.values

In [28]:
print(type(arr))

<class 'numpy.ndarray'>


In [31]:
print(type(arr[3]))

<class 'str'>


In [ ]:
# How come Pandas is able to store hetergeneous data

## Slicing

In [33]:
A

a    10
b    20
c    30
d    40
dtype: object

In [34]:
A['a':'c']

a    10
b    20
c    30
dtype: object

In [35]:
A[0:2]

a    10
b    20
dtype: object

In [36]:
#iloc implicit index
#loc explicit index



In [37]:
A.iloc[0:2]

a    10
b    20
dtype: object

In [39]:
A.loc['a':'c']

a    10
b    20
c    30
dtype: object

In [40]:
# from Dictionary

In [42]:
height_dict = {"A":10,"B":20,"C":30}

In [43]:
height = pd.Series(height_dict)

In [44]:
height

A    10
B    20
C    30
dtype: int64

In [47]:
weight_dict = {'A':100,'B':110,'C':150}

In [48]:
weight = pd.Series(weight_dict)

In [50]:
weight

A    100
B    110
C    150
dtype: int64

## DataFrame

In [51]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])

In [53]:
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [55]:
print(df.values)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [56]:
print(type(df.values))

<class 'numpy.ndarray'>


In [57]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [58]:
df.columns

RangeIndex(start=0, stop=3, step=1)

In [59]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],index=["A","B","C"])

In [60]:
df

0  1  2
A  1  2  3
B  4  5  6
C  7  8  9

In [61]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],index=["A","B","C"],columns = ['c1','c2','c3'])

In [62]:
df

c1  c2  c3
A   1   2   3
B   4   5   6
C   7   8   9

In [63]:
height

A    10
B    20
C    30
dtype: int64

In [64]:
weight

A    100
B    110
C    150
dtype: int64

In [66]:
df = pd.DataFrame({'Height':height,'weight':weight})

In [67]:
df

Height  weight
A      10     100
B      20     110
C      30     150

In [68]:
print(df.index)

Index(['A', 'B', 'C'], dtype='object')


In [69]:
print(df.columns)

Index(['Height', 'weight'], dtype='object')
