<a href="https://colab.research.google.com/github/aman5898/Data-Science-January/blob/main/Pandas/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

## Series

In [5]:
A = pd.Series([10,20,33,44])

In [6]:
A

0    10
1    20
2    33
3    44
dtype: int64

In [7]:
print(A.values)

[10 20 33 44]


In [8]:
type(A)

pandas.core.series.Series

In [9]:
type(A.values)

numpy.ndarray

In [10]:
print(A.index)

RangeIndex(start=0, stop=4, step=1)


In [11]:
print(type(A.index))

<class 'pandas.core.indexes.range.RangeIndex'>


In [75]:
A = pd.Series([10,20,30,"40"],index = ['a','b','c','d'])

In [76]:
A

a    10
b    20
c    30
d    40
dtype: object

In [77]:
print(A.values)

[10 20 30 '40']


In [27]:
arr = A.values

In [28]:
print(type(arr))

<class 'numpy.ndarray'>


In [31]:
print(type(arr[3]))

<class 'str'>


## Slicing

In [33]:
A

a    10
b    20
c    30
d    40
dtype: object

In [34]:
A['a':'c']

a    10
b    20
c    30
dtype: object

In [35]:
A[0:2]

a    10
b    20
dtype: object

In [36]:
#iloc implicit index
#loc explicit index



In [37]:
A.iloc[0:2]

a    10
b    20
dtype: object

In [39]:
A.loc['a':'c']

a    10
b    20
c    30
dtype: object

In [40]:
# from Dictionary

In [42]:
height_dict = {"A":10,"B":20,"C":30}

In [43]:
height = pd.Series(height_dict)

In [44]:
height

A    10
B    20
C    30
dtype: int64

In [47]:
weight_dict = {'A':100,'B':110,'C':150}

In [48]:
weight = pd.Series(weight_dict)

In [50]:
weight

A    100
B    110
C    150
dtype: int64

## DataFrame

In [51]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])

In [53]:
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [55]:
print(df.values)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [56]:
print(type(df.values))

<class 'numpy.ndarray'>


In [57]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [58]:
df.columns

RangeIndex(start=0, stop=3, step=1)

In [59]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],index=["A","B","C"])

In [60]:
df

0  1  2
A  1  2  3
B  4  5  6
C  7  8  9

In [61]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],index=["A","B","C"],columns = ['c1','c2','c3'])

In [62]:
df

c1  c2  c3
A   1   2   3
B   4   5   6
C   7   8   9

In [63]:
height

A    10
B    20
C    30
dtype: int64

In [64]:
weight

A    100
B    110
C    150
dtype: int64

In [95]:
df = pd.DataFrame({'Height':height,'weight':weight})

In [96]:
df

Height  weight
A      10     100
B      20     110
C      30     150

In [68]:
print(df.index)

Index(['A', 'B', 'C'], dtype='object')


In [69]:
print(df.columns)

Index(['Height', 'weight'], dtype='object')


In [78]:
df

Height  weight
A      10     100
B      20     110
C      30     150

In [80]:
df.loc['B':'C']

Height  weight
B      20     110
C      30     150

In [81]:
df.iloc[1:3]

Height  weight
B      20     110
C      30     150

In [85]:
df[['Height']]

Height
A      10
B      20
C      30

In [100]:
df

Height  weight
A      10     100
C      30     150

In [102]:
df[[True,False]]

Height  weight
A      10     100

In [90]:
df[df['Height']>15]

Height  weight
B      20     110
C      30     150

In [97]:
df["Test"] = df['Height']*10

In [92]:
df

Height  weight  Test
A      10     100   100
B      20     110   200
C      30     150   300

In [93]:
del df['Height']

In [94]:
df

weight  Test
A     100   100
B     110   200
C     150   300

In [98]:
df.drop(columns = ["Test"],index=['B'],inplace = True)

In [99]:
df

Height  weight
A      10     100
C      30     150

In [103]:
df = pd.DataFrame({
    'Height': height,
    'Weight': weight,
})
df

Height  Weight
A      10     100
B      20     110
C      30     150

In [104]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, A to C
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Height  3 non-null      int64
 1   Weight  3 non-null      int64
dtypes: int64(2)
memory usage: 152.0+ bytes


In [105]:
df.head()

Height  Weight
A      10     100
B      20     110
C      30     150

In [106]:
df.head(1)

Height  Weight
A      10     100

In [107]:
df.tail(2)

Height  Weight
B      20     110
C      30     150

In [108]:
df.describe()

Height      Weight
count     3.0    3.000000
mean     20.0  120.000000
std      10.0   26.457513
min      10.0  100.000000
25%      15.0  105.000000
50%      20.0  110.000000
75%      25.0  130.000000
max      30.0  150.000000

## Missing Data

In [109]:
dict1 = {'A': 48, 'C':69}
dict2 = {'B':5.8, 'C':6.2}
dict3 = {'A': 10, 'B':15, 'C':12}

In [115]:
df = pd.DataFrame({"Height":dict1,"Weight":dict2,"Age":dict3})

In [116]:
df

Height  Weight  Age
A    48.0     NaN   10
C    69.0     6.2   12
B     NaN     5.8   15

In [113]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, A to B
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Height  2 non-null      float64
 1   Weight  2 non-null      float64
 2   Age     3 non-null      int64  
dtypes: float64(2), int64(1)
memory usage: 176.0+ bytes


In [114]:
df.dropna(axis=1)

Age
A   10
C   12
B   15

In [117]:
df

Height  Weight  Age
A    48.0     NaN   10
C    69.0     6.2   12
B     NaN     5.8   15

In [118]:
df['Height'].fillna(df['Height'].mean(),inplace=True)

In [119]:
df

Height  Weight  Age
A    48.0     NaN   10
C    69.0     6.2   12
B    58.5     5.8   15

In [126]:
df.loc['A'].fillna(30, inplace = True)

/usr/local/lib/python3.7/dist-packages/pandas/core/series.py:4536: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,


In [128]:
df

Height  Weight  Age
A    48.0     NaN   10
C    69.0     6.2   12
B    58.5     5.8   15

In [ ]:
#Update the Value of Weight of A